version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:3050"

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
      - "4040:4040"
    volumes:
      - /api/node_modules
      - ./api:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
